# Generated by Django 3.2 on 2021-04-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='phone_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
