# Generated by Django 3.2 on 2021-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210422_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
