# Generated by Django 3.2 on 2021-04-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
